### ISSUE TITLE
password must contain the answer to this riddle: random riddle

### ISSUE THREAD

**Issue by angusmason** [angusmason/createapassword#31]

**Comment by circles-png** [comment]
put some riddles here

**Comment by angusmason** [comment]
Q: If all Wibbles are Criggles, all Borkins are Kwumblins, no Hoggles are Borkins, and all Criggles are Borkins, is it true that all Borkins are Criggles?

A: No

**Comment by angusmason** [comment]
Q: What are the next three letters in this combination? OTTFFSS.

A: ENT

**Comment by angusmason** [comment]
Q: A butcher stands six feet and one inch tall and wears size 12 shoes. What does he weigh?

A: Meat

**Comment by circles-png** [comment]
so just ga
