### ISSUE TITLE
password must contain username backwards

### ISSUE THREAD

**Issue by angusmason** [angusmason/createapassword#36]

**Comment by angusmason** [comment]
so the username's gonna have conditions so it can't just be "a"

**Comment by circles-png** [comment]
this requires all `Condition` closures to include a username parameter
```diff
- pub type Condition = (Box<dyn Fn(&String) -> bool>, Html);
+ pub type Condition = (Box<dyn Fn(&String, String) -> bool>, Html);
```
which is starting to be a bit repetitive but how else would we store closures
