### ISSUE TITLE
Padding still broken for error messages

### ISSUE THREAD

**Issue by angusmason** [angusmason/createapassword#37]
Used to look like this: 
<img width="1552" alt="IMG_4844" src="https://github.com/angusmason/createapassword/assets/100268469/8fe6bac5-c791-419f-8c00-794a52f5d7df">

Now looks like this:
<img width="1552" alt="image" src="https://github.com/angusmason/createapassword/assets/100268469/8b139e98-db1c-4a01-8d79-809eeeed3400">

**Comment by circles-png** [comment]
![image](https://github.com/angusmason/createapassword/assets/27723996/4d500129-8cce-4267-b65e-2573fcf5d8f8)

**Comment by circles-png** [comment]
fixed in 39e2fe99f60962b97a5843948784545906ddcd90
